// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyConcierge.Infrastructure;

#nullable disable

namespace MyConcierge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329195131_LoyerAccepteNull")]
    partial class LoyerAccepteNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyConcierge.Domain.Models.ContratsLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocataireId")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UniteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocataireId");

                    b.HasIndex("UniteId");

                    b.ToTable("ContratsLocations", (string)null);
                });

            modelBuilder.Entity("MyConcierge.Domain.Models.TypeEntite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categorie")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeEntites", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categorie = 1,
                            Description = "Personne qui loue une unité",
                            Nom = "Locataire"
                        },
                        new
                        {
                            Id = 2,
                            Categorie = 1,
                            Description = "Personne qui possède une unité",
                            Nom = "Propriétaire"
                        },
                        new
                        {
                            Id = 3,
                            Categorie = 1,
                            Description = "Personne qui gère les propriétés",
                            Nom = "Gestionnaire"
                        },
                        new
                        {
                            Id = 4,
                            Categorie = 0,
                            Description = "Unité résidentielle autonome",
                            Nom = "Appartement"
                        },
                        new
                        {
                            Id = 5,
                            Categorie = 0,
                            Description = "Chambre dans un logement partagé",
                            Nom = "Chambre"
                        },
                        new
                        {
                            Id = 6,
                            Categorie = 0,
                            Description = "Bâtiment contenant plusieurs unités",
                            Nom = "Immeuble"
                        },
                        new
                        {
                            Id = 7,
                            Categorie = 2,
                            Description = "Contrat de location d'un an",
                            Nom = "Bail annuel"
                        },
                        new
                        {
                            Id = 8,
                            Categorie = 2,
                            Description = "Contrat de location mois par mois",
                            Nom = "Bail mensuel"
                        });
                });

            modelBuilder.Entity("MyConcierge.Domain.Models.Unite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("MontantLoyer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ParentUniteId")
                        .HasColumnType("int");

                    b.Property<int>("ProprietaireId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TypeEntiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentUniteId");

                    b.HasIndex("ProprietaireId");

                    b.HasIndex("TypeEntiteId");

                    b.ToTable("Unites", (string)null);
                });

            modelBuilder.Entity("MyConcierge.Domain.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeEntiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeEntiteId");

                    b.ToTable("Utilisateurs", (string)null);
                });

            modelBuilder.Entity("MyConcierge.Domain.Models.ContratsLocation", b =>
                {
                    b.HasOne("MyConcierge.Domain.Models.Utilisateur", "Locataire")
                        .WithMany()
                        .HasForeignKey("LocataireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyConcierge.Domain.Models.Unite", "Unite")
                        .WithMany()
                        .HasForeignKey("UniteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locataire");

                    b.Navigation("Unite");
                });

            modelBuilder.Entity("MyConcierge.Domain.Models.Unite", b =>
                {
                    b.HasOne("MyConcierge.Domain.Models.Unite", "ParentUnite")
                        .WithMany()
                        .HasForeignKey("ParentUniteId");

                    b.HasOne("MyConcierge.Domain.Models.Utilisateur", "Proprietaire")
                        .WithMany()
                        .HasForeignKey("ProprietaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyConcierge.Domain.Models.TypeEntite", "TypeEntite")
                        .WithMany()
                        .HasForeignKey("TypeEntiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentUnite");

                    b.Navigation("Proprietaire");

                    b.Navigation("TypeEntite");
                });

            modelBuilder.Entity("MyConcierge.Domain.Models.Utilisateur", b =>
                {
                    b.HasOne("MyConcierge.Domain.Models.TypeEntite", "TypeEntite")
                        .WithMany()
                        .HasForeignKey("TypeEntiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeEntite");
                });
#pragma warning restore 612, 618
        }
    }
}
